### ISSUE TITLE
Deb package does not include copyright file

### ISSUE THREAD

**Issue by robertauer** [cloudogu/makefiles#22]
When building a deb-Package, no copyright file is included. This leads to the following lintian error (here for the ces-commons package):
```
E: ces-commons: no-copyright-file
N: 
N:    Each binary package has to include a plain file
N:    /usr/share/doc/<pkg>/copyright
N:    
N:    Refer to Debian Policy Manual section 12.5 (Copyright information) for
N:    details.
N:    
N:    Severity: serious, Certainty: certain
N:    
N:    Check: copyright-file, Type: binary
```

**Comment by ppxl** [comment]
This is not a makefiles-repo specific problem and can be solved by the incorporating project. A `copyright` file is highly specific for to the software that is packaged.

For example, `myapp1` will need a different copyright file than `myapp2` because the different software properties which can vary over different projects, usually in these aspects:

- different package name implies a different installation path
   - `/usr/share/doc/myapp1/copyright` vs `/usr/share/doc/myapp2/copyright`
- content of the copyright file
   - again: different package name, different content of the copyright file
   - also different packages might be subject to different copyright policies (proprietary vs MIT vs XYZZY)

That being said, it is totally possible to have a proper `copyright` file per project. All the project needs is to define a copyright file under `$projektRoot/deb/usr/share/doc/copyright` and all is well.

I am going to close this issue as `wontfix`.
